---
- name: Ensure Tailscale repo is enabled.
  block:
    - name: Install GPG key into /usr/share/keyrings
      ansible.builtin.get_url:
        url: https://pkgs.tailscale.com/stable/debian/{{ ansible_facts['distribution_release'] }}.noarmor.gpg
        dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
        mode: "0644"
        owner: root
        group: root

    - name: Add Tailscale repo
      ansible.builtin.apt_repository:
        repo: >
          deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg]
          https://pkgs.tailscale.com/stable/debian {{ ansible_facts['distribution_release'] }} main
        state: present
