---
- name: Converge
  hosts: all
  become: true

  vars_files:
    - vars/key.yml
    - vars/main.yml

  tasks:
    # replace these tasks with whatever you find suitable to test
    - name: "Include palekiwi.tailscale"
      ansible.builtin.include_role:
        name: "palekiwi.tailscale"
