---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: tailscale-rocky9
    box: generic/rocky9
    memory: 512
    cpus: 1
provisioner:
  name: ansible
verifier:
  name: ansible
