---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: tailscale-debian11
    box: generic/debian11
    memory: 256
    cpus: 1
provisioner:
  name: ansible
verifier:
  name: ansible
